package orchestrator

import (
	"fmt"
	"sync"

	"github.com/yashsingh/agrinerve/node/internal/events"
)

type Metrics struct {
	Mu sync.RWMutex

	ActiveNodes          int
	OfflineNodes         int
	DishonestNodes       int
	TotalNodes           int
	TradeProposals       int
	AcceptedTrades       int
	RejectedTrades       int
	TotalConsensusRounds int
	HealthScore          int

	// Auction Metrics
	MatchesGenerated     int
	MarketCycleDurations []int64

	ReplayLog []events.Event
}

func NewMetrics() *Metrics {
	return &Metrics{
		ReplayLog: make([]events.Event, 0),
	}
}

func (o *Orchestrator) StartMetricsListener() {
	o.Metrics = NewMetrics()
	go func() {
		for ev := range events.Bus {
			o.Metrics.Mu.Lock()
			o.Metrics.ReplayLog = append(o.Metrics.ReplayLog, ev)
			o.Metrics.Mu.Unlock()

			o.processEvent(ev)
			o.printTrace(ev)
		}
	}()
}

func (o *Orchestrator) processEvent(ev events.Event) {
	o.Metrics.Mu.Lock()
	defer o.Metrics.Mu.Unlock()

	switch ev.Type {
	case events.TradeProposalCreated:
		o.Metrics.TradeProposals++
	case events.ConsensusAccepted:
		o.Metrics.AcceptedTrades++
	case events.ConsensusRejected:
		o.Metrics.RejectedTrades++
	case events.ConsensusRoundCompleted:
		o.Metrics.TotalConsensusRounds++
	case events.MatchGenerated:
		o.Metrics.MatchesGenerated++
	case events.MarketCycleCompleted:
		payload := ev.Payload.(map[string]interface{})
		dur := payload["durationMs"].(int64)
		o.Metrics.MarketCycleDurations = append(o.Metrics.MarketCycleDurations, dur)
	}

	// Dynamic update of node counts
	o.mu.RLock()
	defer o.mu.RUnlock()
	active, offline, dishonest := 0, 0, 0
	for _, n := range o.Nodes {
		if !n.IsAlive() {
			offline++
		} else if n.IsDishonest() {
			dishonest++
		} else {
			active++
		}
	}
	o.Metrics.TotalNodes = len(o.Nodes)
	o.Metrics.ActiveNodes = active
	o.Metrics.OfflineNodes = offline
	o.Metrics.DishonestNodes = dishonest
}

func (o *Orchestrator) GetHealthScore() int {
	o.Metrics.Mu.RLock()
	defer o.Metrics.Mu.RUnlock()

	if o.Metrics.TotalNodes == 0 {
		return 0
	}

	activeRatio := float64(o.Metrics.ActiveNodes+o.Metrics.DishonestNodes) / float64(o.Metrics.TotalNodes)
	
	consensusSuccessRate := 1.0
	totalTrades := o.Metrics.AcceptedTrades + o.Metrics.RejectedTrades
	if totalTrades > 0 {
		consensusSuccessRate = float64(o.Metrics.AcceptedTrades) / float64(totalTrades)
	}

	honestRatio := 1.0
	if o.Metrics.ActiveNodes+o.Metrics.DishonestNodes > 0 {
		honestRatio = float64(o.Metrics.ActiveNodes) / float64(o.Metrics.ActiveNodes+o.Metrics.DishonestNodes)
	}

	score := (activeRatio * 40) + (consensusSuccessRate * 40) + (honestRatio * 20)
	return int(score)
}

func (o *Orchestrator) GetMetrics() *Metrics {
	return o.Metrics
}

func (o *Orchestrator) printTrace(ev events.Event) {
	timeStr := ev.Timestamp.Format("15:04:05")
	var desc string

	switch ev.Type {
	case events.TradeProposalCreated:
		desc = "Trade Proposal Created"
	case events.ConsensusRoundCompleted:
		payload := ev.Payload.(map[string]interface{})
		desc = fmt.Sprintf("Consensus Round %d", payload["round"])
	case events.ConsensusAccepted:
		desc = "Trade Accepted"
	case events.ConsensusRejected:
		desc = "Trade Rejected"
	case events.MatchGenerated:
		desc = "Match Generated by Engine"
	case events.TradeSubmittedToConsensus:
		desc = "Trade Submitted to Consensus"
	case events.MarketCycleCompleted:
		payload := ev.Payload.(map[string]interface{})
		desc = fmt.Sprintf("Market Cycle Completed: Generated %v Matches in %v ms", payload["matchesGenerated"], payload["durationMs"])
	case events.ChaosTriggered:
		payload := ev.Payload.(map[string]interface{})
		desc = fmt.Sprintf("Chaos Triggered: %s %d%% (%d nodes)", payload["action"], payload["percentage"], payload["nodesAffected"])
	case events.DishonestNodeInjected:
		payload := ev.Payload.(map[string]interface{})
		desc = fmt.Sprintf("Dishonest Nodes Injected: %d", payload["count"])
	default:
		return // Don't print spammy events like VoteCast
	}

	fmt.Printf("[%s] %s\n", timeStr, desc)
}
